// ==========================================
// Creature Data Definitions & Biology Stats
// 8 Progressive Bosses
// ==========================================

const CREATURE_DATABASE = [
  {
    id: 'truxalis',
    stageNumber: 1,
    name: 'Truxalis',
    nameEn: 'Truxalis',
    georgianName: 'ტრუქსალისი',
    scientificName: 'Truxalis nasuta',
    avatar: '🦗',
    maxHp: 100,
    speed: 3.5,
    attackPower: 8,
    defense: 2,
    size: { width: 110, height: 50 },
    primaryColor: '#8cb369',
    secondaryColor: '#d4a373',
    accentColor: '#f4a261',
    habitat: 'savanna',
    lore: 'ტრუქსალისი გამოირჩევა დამახასიათებელი კონუსისებრი წაგრძელებული თავითა და ბრტყელი ულვაშებით. ის ცხოვრობს მშრალ ველებზე და საფრთხის დროს მაღალი ნახტომებითა და ეკლიანი უკანა ფეხების ძლიერი წიხლებით იგერიებს მტრებს.',
    loreKa: 'ტრუქსალისი გამოირჩევა დამახასიათებელი კონუსისებრი წაგრძელებული თავითა და ბრტყელი ულვაშებით. ის ცხოვრობს მშრალ ველებზე და საფრთხის დროს მაღალი ნახტომებითა და ეკლიანი უკანა ფეხების ძლიერი წიხლებით იგერიებს მტრებს.',
    loreEn: 'Truxalis is renowned for its distinctive conical elongated head and flattened sword-like antennae. Thriving in dry grasslands, it defends against predators using towering leaps and powerful kicks from its spiny hind legs.',
    tip: 'ტრუქსალისი ჰაერში ხტება და წიხლს ურტყამს. როცა ის ნახტომს აკეთებს, გამოიყენეთ ბლოკი (L) ან ჩაუსაფრდით და დაარტყით დაცემისას!',
    tipKa: 'ტრუქსალისი ჰაერში ხტება და წიხლს ურტყამს. როცა ის ნახტომს აკეთებს, გამოიყენეთ ბლოკი (L) ან ჩაუსაფრდით და დაარტყით დაცემისას!',
    tipEn: 'Truxalis leaps skyward to deliver airborne kicks. When it jumps, raise your Block (L) or pounce and strike right as it lands!',
    moves: ['hop_evade', 'spring_kick', 'mandible_nip'],
    aiCooldowns: { attack: 90 }
  },
  {
    id: 'oedipoda',
    stageNumber: 2,
    name: 'Oedipoda caerulescens',
    nameEn: 'Blue-winged Grasshopper',
    georgianName: 'ლურჯფრთიანი კალია',
    scientificName: 'Oedipoda caerulescens',
    avatar: '🦗',
    maxHp: 125,
    speed: 4.2,
    attackPower: 11,
    defense: 3,
    size: { width: 105, height: 55 },
    primaryColor: '#7f7f7f',
    secondaryColor: '#4cc9f0',
    accentColor: '#0077b6',
    habitat: 'gravel_steppe',
    lore: 'ეს კალია ქვიან გარემოში თითქმის შეუმჩნეველია თავისი მორუხო შენიღბვით. თუმცა შეტევის ან გაფრენისას უცაბედად შლის კაშკაშა ცისფერ-ლურჯ ფრთებს, რაც მტაცებელს თვალს ჭრის და აბნევს.',
    loreKa: 'ეს კალია ქვიან გარემოში თითქმის შეუმჩნეველია თავისი მორუხო შენიღბვით. თუმცა შეტევის ან გაფრენისას უცაბედად შლის კაშკაშა ცისფერ-ლურჯ ფრთებს, რაც მტაცებელს თვალს ჭრის და აბნევს.',
    loreEn: 'This grasshopper is virtually undetectable on stony steppe ground thanks to its speckled gray camouflage. When threatened or taking flight, it flashes brilliant sky-blue hindwings to startle and confuse pursuing predators.',
    tip: 'როცა ლურჯფრთიანი კალია ფრთებს გაშლის (Blue Flash Dash), ის მომენტალურად ზურგს უკან გადაგირბენთ ან მტვერს შემოგაყრით. იყავით მზად მობრუნებისა და კონტრშეტევისთვის!',
    tipKa: 'როცა ლურჯფრთიანი კალია ფრთებს გაშლის (Blue Flash Dash), ის მომენტალურად ზურგს უკან გადაგირბენთ ან მტვერს შემოგაყრით. იყავით მზად მობრუნებისა და კონტრშეტევისთვის!',
    tipEn: 'When the blue-winged grasshopper spreads its wings (Blue Flash Dash), it dashes behind you or kicks up blinding gravel. Be ready to pivot and strike back immediately!',
    moves: ['blue_flash_dash', 'gravel_kick', 'chitin_snap'],
    aiCooldowns: { attack: 80 }
  },
  {
    id: 'calliptamus',
    stageNumber: 3,
    name: 'Calliptamus italicus',
    nameEn: 'Italian Locust',
    georgianName: 'იტალიური კალია',
    scientificName: 'Calliptamus italicus',
    avatar: '🦗',
    maxHp: 155,
    speed: 3.2,
    attackPower: 14,
    defense: 5,
    size: { width: 125, height: 65 },
    primaryColor: '#8a5a36',
    secondaryColor: '#d62828',
    accentColor: '#f77f00',
    habitat: 'mediterranean_scrub',
    lore: 'ძლიერი, ჯავშნოსანი იტალიური კალია. გააჩნია ვარდისფერ-მეწამული შიდა ფრთები და ძლიერი საღეჭი ყბები. ის იყენებს თავის მასას მიწაზე მძიმე დარტყმებისა და გაქანებული შეჯახებისთვის.',
    loreKa: 'ძლიერი, ჯავშნოსანი იტალიური კალია. გააჩნია ვარდისფერ-მეწამული შიდა ფრთები და ძლიერი საღეჭი ყბები. ის იყენებს თავის მასას მიწაზე მძიმე დარტყმებისა და გაქანებული შეჯახებისთვის.',
    loreEn: 'A heavily built, armored locust sporting bright rose-red inner wings and mighty crushing mandibles. It utilizes its heavy body mass to generate thunderous ground stomps and high-speed freight-train charges.',
    tip: 'იტალიური კალიის გაქანებული შეჯახება (Charge) დიდ ზიანს აყენებს. გადაახტით მას (W) და ჰაერიდან დაუშვით ნამგალა თათები!',
    tipKa: 'იტალიური კალიის გაქანებული შეჯახება (Charge) დიდ ზიანს აყენებს. გადაახტით მას (W) და ჰაერიდან დაუშვით ნამგალა თათები!',
    tipEn: 'The Italian Locust charge causes crushing damage. Jump over it (W) and slash down from above with your raptorial limbs!',
    moves: ['ground_stomp', 'red_wing_charge', 'mandible_crush'],
    aiCooldowns: { attack: 85 }
  },
  {
    id: 'katydid',
    stageNumber: 4,
    name: 'Katydid',
    nameEn: 'Katydid',
    georgianName: 'მწვანე კუტკალია',
    scientificName: 'Tettigoniidae (Katydid)',
    avatar: '🍃',
    maxHp: 185,
    speed: 3.8,
    attackPower: 17,
    defense: 6,
    size: { width: 130, height: 70 },
    primaryColor: '#2d6a4f',
    secondaryColor: '#52b788',
    accentColor: '#d8f3dc',
    habitat: 'rainforest_canopy',
    lore: 'კუტკალია შესანიშნავად ბაძავს მწვანე ფოთოლს. ის ფრთების ხახუნით (სტრიდულაციით) გამოსცემს გამჭოლ ულტრაბგერით ხმას, რომელსაც შეუძლია მოწინააღმდეგის დეზორიენტაცია, ხოლო მისი ყბები საოცრად მჭრელია.',
    loreKa: 'კუტკალია შესანიშნავად ბაძავს მწვანე ფოთოლს. ის ფრთების ხახუნით (სტრიდულაციით) გამოსცემს გამჭოლ ულტრაბგერით ხმას, რომელსაც შეუძლია მოწინააღმდეგის დეზორიენტაცია, ხოლო მისი ყბები საოცრად მჭრელია.',
    loreEn: 'The katydid is a master of camouflage, perfectly replicating a green leaf. By rubbing its wings together (stridulation), it produces piercing ultrasonic sound pulses that disorient foes, backed by razor-sharp carnivorous mandibles.',
    tip: 'როცა კუტკალია სტრიდულაციას იწყებს (აკუსტიკური ხმოვანი ტალღები), დაიცავით თავი ბლოკით (L) რათა თავბრუსხვევა და შენელება აიცილოთ!',
    tipKa: 'როცა კუტკალია სტრიდულაციას იწყებს (აკუსტიკური ხმოვანი ტალღები), დაიცავით თავი ბლოკით (L) რათა თავბრუსხვევა და შენელება აიცილოთ!',
    tipEn: 'When the Katydid begins stridulating (acoustic sonic rings), hold Block (L) to guard against dizziness and crippling speed reduction!',
    moves: ['leaf_shield', 'sonic_stridulation', 'leaf_pounce'],
    aiCooldowns: { attack: 75 }
  },
  {
    id: 'hyla_orientalis',
    stageNumber: 5,
    name: 'Hyla orientalis',
    nameEn: 'Eastern Tree Frog',
    georgianName: 'აღმოსავლური ვასაკა',
    scientificName: 'Hyla orientalis',
    avatar: '🐸',
    maxHp: 220,
    speed: 3.6,
    attackPower: 20,
    defense: 4,
    size: { width: 135, height: 80 },
    primaryColor: '#38b000',
    secondaryColor: '#9ef01a',
    accentColor: '#007200',
    habitat: 'mossy_pond',
    lore: 'აღმოსავლური ვასაკა პატარა, გლუვკანიანი ხის ბაყაყია: ოქროსფერი ჰორიზონტალური გუგა, მუქი გვერდითი ზოლი, ყვითელი ბარძაყის შიდა მხარე და წებოვანი თითის დისკები ტოტებზე ცოცვაში ეხმარება. ის ჯერ ხის ტოტიდან ეშვება, შემდეგ კი ძლიერი უკანა ფეხებით განმეორებით ხტება და ნადავლს გრძელი ენით იტაცებს.',
    loreKa: 'აღმოსავლური ვასაკა პატარა, გლუვკანიანი ხის ბაყაყია: ოქროსფერი ჰორიზონტალური გუგა, მუქი გვერდითი ზოლი, ყვითელი ბარძაყის შიდა მხარე და წებოვანი თითის დისკები ტოტებზე ცოცვაში ეხმარება. ის ჯერ ხის ტოტიდან ეშვება, შემდეგ კი ძლიერი უკანა ფეხებით განმეორებით ხტება და ნადავლს გრძელი ენით იტაცებს.',
    loreEn: 'The eastern tree frog is a small, smooth-skinned amphibian: golden horizontal pupils, dark eye stripes, bright yellow inner thighs, and suction-cup toe pads for arboreal mobility. It drops from perches, launches powerful hops, and snatches prey with a lightning-fast tongue whip.',
    tip: 'ბაყაყი ბრძოლას ტოტზე იწყებს და მცირე დაყოვნების შემდეგ აუზთან ჩამოხტება. მიწაზე დაშვების შემდეგ მისი მთავარი საფრთხე გრძელი hop-ებია — დაბლოკეთ დაშვების მომენტი, შემდეგ კი ენის გასროლისას კონტრშეტევა გამოიყენეთ!',
    tipKa: 'ბაყაყი ბრძოლას ტოტზე იწყებს და მცირე დაყოვნების შემდეგ აუზთან ჩამოხტება. მიწაზე დაშვების შემდეგ მისი მთავარი საფრთხე გრძელი hop-ებია — დაბლოკეთ დაშვების მომენტი, შემდეგ კი ენის გასროლისას კონტრშეტევა გამოიყენეთ!',
    tipEn: 'The frog drops down from the high branch. Its long leaps and tongue grappling are dangerous — block the jump landing, then counter when its tongue extends!',
    moves: ['branch_drop', 'frog_hop', 'tongue_grapple', 'body_slam'],
    aiCooldowns: { attack: 70 }
  },
  {
    id: 'asian_hornet',
    stageNumber: 6,
    name: 'Asian Giant Hornet',
    nameEn: 'Asian Giant Hornet',
    georgianName: 'აზიური გიგანტური კრაზანა',
    scientificName: 'Vespa mandarinia',
    avatar: '🐝',
    maxHp: 250,
    speed: 5.2,
    attackPower: 24,
    defense: 5,
    size: { width: 120, height: 75 },
    primaryColor: '#e85d04',
    secondaryColor: '#ffba08',
    accentColor: '#212529',
    habitat: 'hornet_canopy',
    lore: 'მწერების სამყაროს ნამდვილი საჰაერო ტერორი. დიდი ნარინჯისფერი თავით, მუქი ჯავშნიანი მკერდით, შავ-ოქროსფერი ზოლიანი მუცლით, ძლიერი მანდიბულებითა და ნესტრით გამოირჩევა.',
    loreKa: 'მწერების სამყაროს ნამდვილი საჰაერო ტერორი. დიდი ნარინჯისფერი თავით, მუქი ჯავშნიანი მკერდით, შავ-ოქროსფერი ზოლიანი მუცლით, ძლიერი მანდიბულებითა და ნესტრით გამოირჩევა.',
    loreEn: 'The undisputed aerial apex terror of the insect world. Armed with a large orange head, armored dark thorax, predatory serrated mandibles, and a potent curved stinger that delivers tissue-destroying venom.',
    tip: 'კრაზანა ჰაერშია და ძნელი მისაწვდომია! ახლოს ყოფნისას მის მანდიბულებს გაუფრთხილდით, ხოლო საშუალო დისტანციაზე — მოხრილ ნესტრის შეტევას.',
    tipKa: 'კრაზანა ჰაერშია და ძნელი მისაწვდომია! ახლოს ყოფნისას მის მანდიბულებს გაუფრთხილდით, ხოლო საშუალო დისტანციაზე — მოხრილ ნესტრის შეტევას.',
    tipEn: 'The hornet hovers mid-air and is difficult to hit! Watch out for its close-range mandibles, and beware of its curved stinger divebomb at mid-range.',
    moves: ['aerial_divebomb', 'stinger_thrust', 'venom_drips'],
    aiCooldowns: { attack: 65 }
  },
  {
    id: 'pharaoh_ants',
    stageNumber: 7,
    name: 'Pharaoh Ants Colony',
    nameEn: 'Pharaoh Ants Colony',
    georgianName: 'ფარაონის ჭიანჭველების გუნდი',
    scientificName: 'Monomorium pharaonis group',
    avatar: '🐜',
    maxHp: 280,
    speed: 4.8,
    attackPower: 22,
    defense: 3,
    size: { width: 110, height: 60 },
    primaryColor: '#c1121f',
    secondaryColor: '#780000',
    accentColor: '#fdf0d5',
    habitat: 'anthill_chambers',
    lore: 'ფარაონის ჭიანჭველები ერთობლივი ძალებით უძლეველ გუნდს ქმნიან. მთავარი მეომარი ხელმძღვანელობს მუშების ხროვას, რომლებიც ფეხებზე ეკიდებიან მანტისს, ანელებენ მას და მჟავას (Formic Acid) აფრქვევენ.',
    loreKa: 'ფარაონის ჭიანჭველები ერთობლივი ძალებით უძლეველ გუნდს ქმნიან. მთავარი მეომარი ხელმძღვანელობს მუშების ხროვას, რომლებიც ფეხებზე ეკიდებიან ჩოქელას, ანელებენ მას და მჟავას (Formic Acid) აფრქვევენ.',
    loreEn: 'Pharaoh ants fight as an unified collective superorganism. A heavily armored soldier leads waves of worker ants that cling to prey limbs to restrict movement while spraying corrosive formic acid.',
    tip: 'ეს არის ხროვული ბრძოლა! გამოიყენეთ ჩოქელას სამმაგი ჭრა (J) და ჩასაფრებიდან ნახტომი (K), რათა ერთდროულად გაანადგუროთ მოზღვავებული ჭიანჭველები!',
    tipKa: 'ეს არის ხროვული ბრძოლა! გამოიყენეთ ჩოქელას სამმაგი ჭრა (J) და ჩასაფრებიდან ნახტომი (K), რათა ერთდროულად გაანადგუროთ მოზღვავებული ჭიანჭველები!',
    tipEn: 'This is a swarm combat! Combine Mantis triple slashes (J) and leaping pounces (K) to wipe out the surrounding ant hordes before they overwhelm you!',
    moves: ['swarm_rush', 'formic_acid_spray', 'soldier_bite'],
    aiCooldowns: { attack: 55 }
  },
  {
    id: 'garter_snake',
    stageNumber: 8,
    name: 'Garter Snake',
    nameEn: 'Garter Snake',
    georgianName: 'ბაღის გველი',
    scientificName: 'Thamnophis sirtalis',
    avatar: '🐍',
    maxHp: 340,
    speed: 4.5,
    attackPower: 28,
    defense: 7,
    size: { width: 180, height: 85 },
    primaryColor: '#2b9348',
    secondaryColor: '#ffd166',
    accentColor: '#1b4332',
    habitat: 'forest_floor',
    lore: 'ხერხემლიანი მტაცებელი — ფინალური გამოცდა მანტისისთვის! გველი S-ფორმით იკეცება და თვალის დახამხამებაში იტყორცნება წინ. მისი გრძელი კუდი მთელ არენას ფარავს, ხოლო სისხარტე და ძალა უმაღლესია.',
    loreKa: 'ხერხემლიანი მტაცებელი — ფინალური გამოცდა ჩოქელასთვის! გველი S-ფორმით იკეცება და თვალის დახამხამებაში იტყორცნება წინ. მისი გრძელი კუდი მთელ არენას ფარავს, ხოლო სისხარტე და ძალა უმაღლესია.',
    loreEn: 'A predatory vertebrate — the ultimate trial for the Mantis! Coiling into an explosive S-shape, it lunges forward faster than the eye can follow. Its long tail sweeps across the arena floor, backed by devastating speed and power.',
    tip: 'გველის S-ლუნჯი ეკრანის უდიდეს ნაწილს ფარავს, კუდის მოქნევა კი მიწაზე გცემთ. გადაახტით კუდის მოქნევას, ჩასაფრებიდან (K) დაარტყით თავს და გამოიყენეთ სამმაგი ჭრა (J)!',
    tipKa: 'გველის S-ლუნჯი ეკრანის უდიდეს ნაწილს ფარავს, კუდის მოქნევა კი მიწაზე გცემთ. გადაახტით კუდის მოქნევას, ჩასაფრებიდან (K) დაარტყით თავს და გამოიყენეთ სამმაგი ჭრა (J)!',
    tipEn: 'The snake’s S-lunge spans across the screen and its tail whip sweeps you off your feet. Jump over the tail, pounce (K) at its head, and unleash rapid triple slashes (J)!',
    moves: ['s_coil_strike', 'tail_whip_sweep', 'constrict_feint'],
    aiCooldowns: { attack: 60 }
  }
];

// Helper to look up creature by stage number (1-based)
function getCreatureByStage(stageNum) {
  const index = Math.max(0, Math.min(stageNum - 1, CREATURE_DATABASE.length - 1));
  return CREATURE_DATABASE[index];
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { CREATURE_DATABASE, getCreatureByStage };
}
